- packages/controls/src/FreeControl.ts
- packages/controls/src/OrbitControl.ts
- packages/controls/src/OrthoControl.ts
- packages/controls/src/Spherical.ts
> Adapter to latest dev/0.8

- packages/controls/src/OrthoControl.ts
- packages/controls/src/inputDevice/IControlInput.ts
> Refactor `OrthoControl` with `InputManager`

- packages/outline/src/OutlineManager.ts
> feat: use replaceMaterial to render outline only

- packages/outline/src/OutlineManager.ts
> Fix outline bug

- packages/auxiliary-lines/src/WireframeManager.ts
> Fix WireFrameManager render bug by turn off vao in wireframe draw

- packages/outline/src/OutlineManager.ts
> Fix outline when entity's transform is changed

- packages/auxiliary-lines/src/WireframeManager.ts
- packages/auxiliary-lines/src/WireframePrimitive.ts
> fix: wireframe index buffer type bug

- packages/framebuffer-picker/src/ColorRenderPass.ts
- packages/framebuffer-picker/src/FramebufferPicker.ts
> refactor: change api

- packages/auxiliary-lines/src/WireframeManager.ts
> feat: rotate light to default forward direction

- packages/outline/src/outline.fs.glsl
* use pure outline color
* use gamma color space
> fix: use pure outline color

- packages/auxiliary-lines/src/WireframeManager.ts
> Fix WireFrame local position and upAxis bug

- packages/auxiliary-lines/src/WireframeManager.ts
> fix: camera NDC z bug

- packages/outline/src/OutlineManager.ts
fix https://github.com/oasis-engine/editor/issues/704
> Fix outline transform error

- packages/outline/src/OutlineManager.ts
fix https://github.com/oasis-engine/editor/issues/773
> fix outline wrap mode error

- packages/outline/src/OutlineManager.ts
WorldMatrix -> LocalMatrix 会有精度损失
> Optimization outline 

- packages/outline/src/OutlineManager.ts
https://github.com/oasis-engine/editor/issues/792
#58
> refactor outline with `layer` and main/sub color 

- packages/controls/src/OrbitControl.ts
Fix the bug that automatic rotation does not take effect.
> Fix: `OrbitControl` auto rotate bug

- packages/gizmo/src/Group.ts
> Fix: center point of multi entities error

- rollup.config.js
- rollup.miniprogram.plugin.js
- [] Docs have been added / updated (for bug fixes / features)
> Fix miniprogram bundle error

- packages/auxiliary-lines/package.json
- packages/auxiliary-lines/src/WireframeManager.ts
- packages/custom-material/src/grid/GridControl.ts
- packages/custom-material/src/index.ts
- packages/custom-material/src/plain-color/PlainColorMaterial.ts
- packages/gizmo/package.json
- packages/gizmo/src/Axis.ts
- packages/gizmo/src/Rotate.ts
- packages/gizmo/src/Type.ts
- packages/gizmo/src/Utils.ts
- packages/navigation-gizmo/package.json
- packages/navigation-gizmo/src/NavigationGizmo.ts
- packages/navigation-gizmo/src/Utils.ts
- packages/outline/package.json
- packages/outline/src/OutlineManager.ts
- packages/skeleton-viewer/src/SkeletonViewer.ts
> adapt new engine settings

- packages/auxiliary-lines/README.md
- packages/custom-material/README.md
- packages/custom-material/src/bake-pbr/README.md
- packages/custom-material/src/grid/README.md
- packages/custom-material/src/plain-color/README.md
- packages/custom-material/src/planar-shadow/README.md
- packages/geometry-sketch/README.md
- packages/oasis-engine-toolkit/README.md
- packages/stats/README.md
> Add readme for each material

- packages/controls/src/FreeControl.ts
fix: freeControl would flip when rotate to top
> fix: freeControl flip error

- packages/navigation-gizmo/src/SphereScript.ts
fix cannot flip back to up direction error
> Fix: cannot flip back to up direction 

- packages/controls/src/OrthoControl.ts
> Fix: change ortho zoom speed algo

- packages/gizmo/src/Gizmo.ts
- packages/gizmo/src/Rotate.ts
- packages/gizmo/src/Type.ts
- packages/gizmo/src/Utils.ts
add free rotate feature to enable rotate in all directions
> feat: add free rotate

- package.json
- packages/auxiliary-lines/package.json
- packages/auxiliary-lines/src/WireframeManager.ts
- packages/controls/package.json
- packages/custom-material/package.json
- packages/custom-material/src/grid/GridControl.ts
- packages/custom-material/src/grid/GridMaterial.ts
- packages/framebuffer-picker/package.json
- packages/gizmo/package.json
- packages/gizmo/src/Axis.ts
- packages/gizmo/src/Type.ts
- packages/navigation-gizmo/package.json
- packages/navigation-gizmo/src/CircleMesh.ts
- packages/navigation-gizmo/src/SphereScript.ts
- packages/outline/package.json
- packages/outline/src/OutlineManager.ts
> enhance grid to support LOD change for distance

- packages/framebuffer-picker/src/FramebufferPicker.ts
> Adapt  FrameBufferPicker to latest engine version

- packages/outline/src/OutlineManager.ts
> Outline Exclude sprite renderer

- packages/gizmo/src/Gizmo.ts
> Feat: add size control for gizmo

- packages/framebuffer-picker/src/FramebufferPicker.ts
> fix: coord calculate error

- packages/gizmo/README.md
- packages/gizmo/src/Gizmo.ts
> Feat: gizmo event

- packages/auxiliary-lines/src/LineDrawer.ts
- packages/framebuffer-picker/src/FramebufferPicker.ts
> Cherry pick: box select into main branch

- packages/auxiliary-lines/package.json
- packages/controls/package.json
- packages/custom-material/package.json
- packages/framebuffer-picker/package.json
- packages/framebuffer-picker/src/FramebufferPicker.ts
- packages/galacean-engine-toolkit/package.json
- packages/geometry-sketch/package.json
- packages/gizmo/package.json
- packages/input-logger/package.json
- packages/lines/package.json
- packages/navigation-gizmo/package.json
- packages/outline/package.json
- packages/skeleton-viewer/package.json
- packages/stats/package.json
- packages/way-point/package.json
> Feat: upgrade version

- package.json
- packages/gizmo/src/Gizmo.ts
- packages/navigation-gizmo/src/NavigationGizmo.ts
update physic init internal api
> fix: update physic init internal api

- packages/tween/README.md
- packages/tween/package.json
- packages/tween/src/Tween.ts
- packages/tween/src/easing.ts
- packages/tween/src/index.ts
- packages/tween/src/interfaces.ts
- packages/tween/tsconfig.json
Add tween for galacean.
https://github.com/galacean/engine-toolkit/assets/7953802/63eb3075-9655-41a3-86c4-bdbb1683e61e
Support all features in tweenjs/tween.js https://github.com/tweenjs/tween.js
> Tween animation component

- package.json
- packages/auxiliary-lines/package.json
- packages/controls/package.json
- packages/custom-gltf-parser/README.md
- packages/custom-gltf-parser/package.json
- packages/custom-gltf-parser/src/index.ts
- packages/custom-gltf-parser/tsconfig.json
- packages/custom-material/package.json
- packages/dynamic-bone/package.json
- packages/framebuffer-picker/package.json
- packages/geometry-sketch/package.json
- packages/gizmo/package.json
- packages/lines/package.json
- packages/navigation-gizmo/package.json
- packages/outline/package.json
- packages/skeleton-viewer/package.json
- packages/stats/package.json
- packages/tween/package.json
- packages/way-point/package.json
> Add custom gltf parser

- packages/stats/src/Core.ts
- packages/stats/src/Monitor.ts
- packages/stats/src/hooks/RequestHook.ts
> feat: support network request

- packages/gizmo/src/Gizmo.ts
- packages/outline/src/OutlineManager.ts
> Change layer

- packages/stats/src/hooks/RequestHook.ts
> Cancel request auto hook

- packages/navigation-gizmo/src/NavigationGizmo.ts
fix: traverse entity and delete cullingmask logic
> Fix navigation gizmo bug

- packages/stats/src/Stats.ts
- packages/stats/src/hooks/RequestHook.ts
> Control Request hook Timing

- README.md
- package.json
- packages/auxiliary-lines/package.json
- packages/controls/package.json
- packages/custom-gltf-parser/package.json
- packages/custom-material/package.json
- packages/draco/README.md
- packages/draco/package.json
- packages/draco/src/DRACOWorker.ts
- packages/draco/src/KHR_draco_mesh_compression.ts
- packages/draco/src/decoder.ts
- packages/draco/src/index.ts
- packages/draco/src/worker/worker.js
- packages/draco/tsconfig.json
- packages/dynamic-bone/package.json
- packages/framebuffer-picker/package.json
- packages/geometry-sketch/package.json
- packages/gizmo/package.json
- packages/input-logger/package.json
- packages/lines/package.json
- packages/navigation-gizmo/package.json
- packages/outline/package.json
- packages/skeleton-viewer/package.json
- packages/stats/package.json
- packages/tween/package.json
- packages/way-point/package.json
- tests/package.json
> Support draco

- packages/auxiliary-lines/src/WireframeManager.ts
take particle shape as null into consideration
> Fix: take particle shape as null into consideration

- README.md
- packages/auxiliary-lines/package.json
- packages/auxiliary-lines/src/WireframePrimitive.ts
- packages/controls/package.json
- packages/custom-gltf-parser/package.json
- packages/custom-material/package.json
- packages/dynamic-bone/package.json
- packages/framebuffer-picker/package.json
- packages/geometry-sketch/package.json
- packages/gizmo/package.json
- packages/input-logger/package.json
- packages/lines/package.json
- packages/navigation-gizmo/package.json
- packages/outline/package.json
- packages/skeleton-viewer/package.json
- packages/stats/package.json
- packages/tween/package.json
- packages/way-point/package.json
fix wireframeMananger direction for circleShape in particle
> Fix: wireframeMananger direction 

- packages/outline/package.json
- rollup.config.mjs
> Fix glsl pack error

- packages/framebuffer-picker/src/FramebufferPicker.ts
adapt to camera and renderTarget aspect ratio implement change in https://github.com/galacean/runtime/pull/1872
> Fix: adapt camera aspect ratio api change

- packages/gizmo/src/Gizmo.ts
add canvas area protect for gizmo, as pointer target could be document in 1.2 engine
> Fix: add canvas area protect for gizmo

- packages/framebuffer-picker/src/FramebufferPicker.ts
- packages/outline/src/outline.vs.glsl
adapter 1.2 api change from https://github.com/galacean/runtime/pull/1997
> refactor FramebufferPicker and Outline to adapter 1.2 api change

- packages/skeleton-viewer/src/SkeletonViewer.ts
mergeError fixed: https://github.com/galacean/runtime-toolkit/pull/240
> refactor: adapter bone api change

- packages/stats/src/hooks/DrawCallHook.ts
**Before:**
**Now:**
`
import { OrbitControl } from "@galacean/engine-toolkit-controls";
import {
Buffer,
BufferBindFlag,
BufferMesh,
BufferUsage,
Camera,
Engine,
IndexFormat,
Material,
Mesh,
MeshRenderer,
Shader,
Vector3,
VertexElement,
VertexElementFormat,
WebGLEngine,
} from "@galacean/engine";
import { Stats } from "@galacean/engine-toolkit-stats";
import { ShaderLab } from "@galacean/engine-shader-lab";
// Create engine
WebGLEngine.create({ canvas: "canvas", shaderLab: new ShaderLab() }).then((engine) => {
engine.canvas.resizeByClientSize();
// Get scene and root entity
const scene = engine.sceneManager.activeScene;
const rootEntity = scene.createRootEntity("Root");
// Init instance shader
const shader = initCustomShaderByShaderLab();
// Create camera
const cameraEntity = …
> feat(DrawCallHook):hook functions of `drawElementsInstanced` and `drawArraysInstanced`

- packages/custom-material/src/bake-pbr/fragment.ts
> bakePBR 1.2 api change

- packages/gizmo/src/Rotate.ts
- packages/gizmo/src/Scale.ts
- packages/gizmo/src/Translate.ts
> Fix: dispatch onMove event

- packages/shaderlab/src/shaders/color_vert.glsl
> Fix pbr shaderlab error

- packages/draco/package.json
> fix: draco export error

- packages/xr/src/trackable/XRTrackedObjectManager.ts
> feat: update code

- packages/gizmo/src/Group.ts
> Fix group listener error

- packages/navigation-gizmo/src/SphereScript.ts
> Update on pointer call back
